version: '3.7'
services:
  mongodb:
    image: mongo:3.6
    container_name: mongo-nuclearis
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db_teste
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - nuclearis-volume:/data/db

volumes:
  nuclearis-volume:
